version: '3'
services:
  rails:
    build: .
    ports:
      - 3000:3000
    # Start the rails server and bind it to 0.0.0.0, which allows it to be accessed from the host
    # system.
    command: rails s -b 0.0.0.0
    volumes:
      # Mount this directory as a volume into the container, so that changes made to it propagate
      # to the container.
      - .:/usr/src/lobsters
  mysql:
    image: mariadb:10.5.4
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
